import "./globals.css";
import StateProvider from "@/redux/stateProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StateProvider>
      <html lang="en">
        <body>
            {children}
        </body>
      </html>
    </StateProvider>
  );
}